### ISSUE TITLE
gulp 监听中经常会中断

### ISSUE THREAD

**Issue by visamz** [xosuperpig/tmodjs-loader#7]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch null EPERM
    at exports._errnoException (util.js:870:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)
```

作者有空看看呗

```
webpack 1.13.1
node  v4.3.1
```

**Comment by visamz** [comment]
写了一个 更好的 loader ，需要的拿去~ https://github.com/byends/art-template-loader
